# Generated by Django 5.0.6 on 2024-06-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='file',
            field=models.FileField(default=2, upload_to='file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitob',
            name='rasm',
            field=models.ImageField(default=2, upload_to='photo'),
            preserve_default=False,
        ),
    ]
