# Generated by Django 5.0.6 on 2024-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_kitob_file_kitob_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
