# Generated by Django 4.2.11 on 2024-06-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_statistika'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistika',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
