# Generated by Django 4.2.11 on 2024-06-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bookdownloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='view',
            field=models.IntegerField(default=2, verbose_name=0),
            preserve_default=False,
        ),
    ]
