# Generated by Django 4.2.11 on 2024-06-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_kitob_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='info',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
